tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "colordiff"
brew "dnsmasq", restart_service: true
brew "ffmpeg"
brew "gnu-sed"
brew "grep"
brew "hostess"
brew "htop"
brew "hugo"
brew "imagemagick"
brew "jq"
brew "libdvdcss"
brew "mysql-client"
brew "mysql@5.7", restart_service: true
brew "nginx", restart_service: true
brew "nmap"
brew "php", restart_service: true
brew "pkg-config"
brew "pssh"
brew "pwgen"
brew "redis", restart_service: true
brew "telnet"
brew "watch"
brew "wget"
brew "yarn"
brew "youtube-dl"
cask "docker"
cask "font-fira-code"
cask "font-source-code-pro"
cask "gimp"
cask "handbrake"
cask "imageoptim"
cask "iterm2"
cask "macdown"
cask "skitch"
cask "telegram-desktop"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
